<?php
$title = 'Edit device';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('device', array('action' => 'edit')));
$form->prepare();

echo "<table>";
echo $this->form()->openTag($form);
echo $this->formRow($form->get('security'));
echo $this->formHidden($form->get('id'));

echo "<tr><td>" . $this->formRow($form->get('name')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('ip')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('snmpCommunity')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('configUsername')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('configPassword')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('modelId')) . "</td></tr>";
echo "<tr><td>" . $this->formRow($form->get('state')) . "</td></tr>";
echo "<tr><td>" . $this->formSubmit($form->get('submit')) . "</td></tr>";
echo "<tr><td>" . $this->form()->closeTag() . "</td></tr>";
echo "</table>";