<?php
$title = 'Edit device';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('device', array('action' => 'edit')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('security'));
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('ip'));
echo $this->formRow($form->get('snmpCommunity'));
echo $this->formRow($form->get('configUsername'));
echo $this->formRow($form->get('configPassword'));
echo $this->formRow($form->get('modelId'));
echo $this->formRow($form->get('state'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();