<?php print $this->showMessages(); ?>

<table id="devices" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Ip address</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>

    <?php
    foreach ($this->devices as $device) {
        print '<tr>'
            . '<td>' . $device['id'] . '</td>'
            . '<td> <a href="' . $this->url('device', array('action' => 'view', 'id' => $device['id'])) . '">' . $device['name'] . '</a></td>'
            . '<td>' . $device['ip'] . '</td>'
            . '<td> <a href="' . $this->url('device', array('action' => 'onuList', 'id' => $device['id'])) . '">ONU list</a> |
                    <a href="' . $this->url('device', array('action' => 'edit', 'id' => $device['id'])) . '">edit</a> |
                   <a href="' . $this->url('device', array('action' => 'delete', 'id' => $device['id'])) . '">delete</a></td>
              </tr>';
    }
    ?>

    </tbody>
    <tfoot>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Ip address</th>
        <th>Actions</th>
    </tr>
    </tfoot>
</table>


<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $('#devices').DataTable({
            "paginate": false,
            "sort": true
        });
    });
</script>