<?php print $this->showMessages(); ?>

<table id="onuList" class="display" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th>OLT</th>
        <th>Port</th>
        <th>MAC ONU</th>
        <th>RxPower(dBm)</th>
        <th>Details</th>
    </tr>
    </thead>
    <tbody>

    <?php
    foreach ($obj as $value) {
        echo "<tr>";
        echo "<td>$value[olt]</td>";
        echo "<td>$value[port]</td>";
        echo "<td>$value[mac_onu]</td>";
        echo "<td>$value[rxp]</td>";
        echo "<td>";
        echo "<a class='btn btn-success' href=../onuDetails/$device[id]/$value[key]>
                <i class='glyphicon glyphicon-zoom-in icon-white'></i> ONU Details
            </a>";
        echo "</td>";
        echo '</tr>';
    }
    ?>

    </tbody>
    <tfoot>
    <tr>
        <th>OLT</th>
        <th>Port</th>
        <th>MAC ONU</th>
        <th>RxPower(dBm)</th>
        <th>Details</th>
    </tr>
    </tfoot>
</table>

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $('#onuList').DataTable({
            "lengthMenu": [[-1, 10, 25, 50], ["All", 10, 25, 50]],
            "dom": '<"top"i>rt<"bottom"flp><"clear">',
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                        .appendTo($(column.header()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );
                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });
                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });
    });
</script>